server:
  port: 8080
  servlet:
    context-path: /jpademo

spring:
  datasource:
    url: "jdbc:p6spy:mysql://127.0.0.1:3306/jpadb?verifyServerCertificate=false&useSSL=false
    &allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8"
    username: test
    password: test
    driver-class-name: "com.p6spy.engine.spy.P6SpyDriver"
    hikari:
      maximum-pool-size: 200
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

logging:
  file:
    path: logs/
  level:
    org.springframework.orm.jpa: debug
    com.glsc: debug
    org.hibernate.SQL: debug